version: '3'


services:

  web:
    build: .
    command: bash -c "flask db init && flask db migrate && flask db upgrade &&
                      flask api download_stars && flask run --host=0.0.0.0"
    volumes:
      - .:/code
    environment:
      - FLASK_APP=starapp
    ports:
      - 5000:5000
    deploy:
      resources:
        limits:
          cpus: '4'
    depends_on:
      - db
      - redis
  
  redis:
    image: redis
    ports: 
      - 6379:6379
  
  db:
    image: postgres:14
    volumes:
      - data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: "star"
      POSTGRES_USER: "admin"
      POSTGRES_PASSWORD: "password"
      POSTGRES_HOST_AUTH_METHOD: "md5"
    ports:
      - 5432:5432


volumes:
  data:
