version: '3'


services:

  web:
    build:
      context: ./src
      dockerfile: Dockerfile.test
    container_name: about_stars_test_web
    command: python3 -m tox -vv -p 3
    volumes:
      - .:/code
    environment:
      - FLASK_APP=./starapp/__init__.py
    env_file:
      - ./config/.env.prod
      - ./config/.env.prod.redis
      - ./config/.env.prod.db
    ports:
      - 5000:5000
    deploy:
      resources:
        limits:
          cpus: '3'
    networks:
      - flask-test
    depends_on:
      - db

  db:
    image: postgres:14
    restart: always
    container_name: about_stars_test_db
    env_file:
      - ./config/.env.prod.db
    volumes:
      - data:/var/lib/postgresql/data
    networks:
      - flask-test
    ports:
      - 5432:5432


volumes:
  data:


networks:
  flask-test: